language: cpp
dist: bionic

install:
  - curl https://openturns.github.io/apt/public.key | sudo apt-key add -
  - echo deb https://openturns.github.io/apt/ubuntu bionic main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
  - sudo apt-get -y install libopenturns-dev python3-openturns python3-dev cmake swig texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python3-matplotlib python3-sphinx python3-numpydoc
  - sudo rm -r /opt/python/*

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local
    -DCMAKE_CXX_FLAGS="-Wall -Wextra"
    -DPYTHON_EXECUTABLE=/usr/bin/python3
    .
  - make install -j2 && make tests -j2 && ctest -j2 --output-on-failure --timeout 100

